### ISSUE TITLE
After executing prepare_all.sh, I encountered an error related to ext4fuse

### ISSUE THREAD

**Issue by cyliustack** [snippits/snippits#2]
After executing prepare_all.sh, I encountered an error shown below,   
(my environment  
Linux:  4.10.8-200.fc25.x86_64  
GCC:  6.3.1  
clang: 3.9.1   )
![screenshot from 2017-07-27 13-26-43](https://user-images.githubusercontent.com/16119365/28655634-c7aa6808-7262-11e7-8bc9-becb0f260d36.png)
Any recommendation to fix the error?

**Comment by MedicineYeh** [comment]
Fixed
